version: 2.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Add Permission
          command: chmod +x gradlew
      - run:
          name: Gradle Build
          command: ./grad;ew bootJar
      - persist_to_workspace:
          root: .
          paths:
            - build/libs/*.jar
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - gradle-build